# Generated by Django 3.2.5 on 2021-07-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='register',
        ),
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='account',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='base.account'),
            preserve_default=False,
        ),
    ]
