# Generated by Django 3.2.6 on 2021-08-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='manager.account'),
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('date', 'time', 'player_id', 'nickname')},
        ),
    ]
