# Generated by Django 3.2.5 on 2021-07-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210730_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['date', 'time']},
        ),
    ]
